; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/micro-ROS/micro_ros_arduino.git
	adafruit/Adafruit NeoPixel@1.11.0
	mikalhart/TinyGPSPlus@1.0.3
	adafruit/Adafruit GFX Library@1.11.3
	adafruit/Adafruit SH110X@2.1.10
	bblanchon/ArduinoJson@^6.21.3
	hideakitai/MPU9250@^0.4.8
	adafruit/Adafruit MPU6050@^2.2.6
	madhephaestus/ESP32Servo@^3.0.9
	adafruit/Adafruit VL53L1X @ ^3.1.1
build_flags = 
	-DMICRO_ROS_TRANSPORT_SERIAL
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_ARCH_ESP32
	-L .pio/libdeps/esp32s3/micro_ros_arduino/src/esp32
	-l microros
lib_archive = false
lib_ldf_mode = deep+
